[[outputs.mqtt]]
  alias = "mqtt_output"
  namepass = ["mqtt_output"]
  servers = ["tcp://127.0.0.1:1883"]
  username = "telegraf"
  password = "…"
  topic = '{{ .Tag "topic" }}'
  data_format = "template"
  template = '{{ .Field "payload" }}'

[[outputs.mqtt]]
  alias = "mqtt_output_retain"
  namepass = ["mqtt_output_retain"]
  servers = ["tcp://127.0.0.1:1883"]
  username = "telegraf"
  password = "…"
  topic = '{{ .Tag "topic" }}'
  data_format = "template"
  template = '{{ .Field "payload" }}'
  retain = true
